// <auto-generated />
using System;
using CupomMaster.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CupomMaster.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CupomMaster.API.Models.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LojaId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeUtilizada")
                        .HasColumnType("int");

                    b.Property<string>("RegrasUso")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoDesconto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("LojaId");

                    b.ToTable("Cupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "BEMVINDO10",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataValidade = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            QuantidadeDisponivel = 100,
                            QuantidadeUtilizada = 15,
                            RegrasUso = "Válido para primeira compra",
                            TipoDesconto = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValorDesconto = 10m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "NATAL2024",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataValidade = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LojaId = 1,
                            QuantidadeDisponivel = 50,
                            QuantidadeUtilizada = 23,
                            RegrasUso = "Válido para compras acima de R$ 200",
                            TipoDesconto = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValorDesconto = 50m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "FRETEGRATIS",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataValidade = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LojaId = 2,
                            QuantidadeDisponivel = 200,
                            QuantidadeUtilizada = 87,
                            RegrasUso = "Desconto no valor do frete",
                            TipoDesconto = 1,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ValorDesconto = 15m
                        });
                });

            modelBuilder.Entity("CupomMaster.API.Models.HistoricoUso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CupomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorPedido")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CupomId");

                    b.HasIndex("LojaId");

                    b.ToTable("HistoricoUsos");
                });

            modelBuilder.Entity("CupomMaster.API.Models.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Lojas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CNPJ = "12.345.678/0001-90",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "centro@lojas.com",
                            Endereco = "Rua das Flores, 123 - Centro",
                            Nome = "Loja Centro",
                            Telefone = "(11) 3000-0001",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CNPJ = "23.456.789/0001-91",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "shopping@lojas.com",
                            Endereco = "Av. Paulista, 1000 - Shopping Center",
                            Nome = "Loja Shopping",
                            Telefone = "(11) 3000-0002",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CNPJ = "34.567.890/0001-92",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "online@lojas.com",
                            Endereco = "E-commerce",
                            Nome = "Loja Online",
                            Telefone = "(11) 3000-0003",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CupomMaster.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CupomMaster.API.Models.Cupom", b =>
                {
                    b.HasOne("CupomMaster.API.Models.Loja", "Loja")
                        .WithMany("Cupons")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("CupomMaster.API.Models.HistoricoUso", b =>
                {
                    b.HasOne("CupomMaster.API.Models.Cupom", "Cupom")
                        .WithMany("HistoricoUsos")
                        .HasForeignKey("CupomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CupomMaster.API.Models.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId");

                    b.Navigation("Cupom");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("CupomMaster.API.Models.Cupom", b =>
                {
                    b.Navigation("HistoricoUsos");
                });

            modelBuilder.Entity("CupomMaster.API.Models.Loja", b =>
                {
                    b.Navigation("Cupons");
                });
#pragma warning restore 612, 618
        }
    }
}
